version: '3'
services:
  csapp:
    image: csapp:latest
    volumes:
      - .:/cs61c
    ports:
      - "8144:22"
      - "6161:6161"
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    stdin_open: true
    tty: true
    command: bash
